// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: proto/paperio.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家坐标
type PaperPlayerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"` // X 坐标
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"` // Y 坐标
}

func (x *PaperPlayerPosition) Reset() {
	*x = PaperPlayerPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperPlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperPlayerPosition) ProtoMessage() {}

func (x *PaperPlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperPlayerPosition.ProtoReflect.Descriptor instead.
func (*PaperPlayerPosition) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{0}
}

func (x *PaperPlayerPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PaperPlayerPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 复活点坐标
type PaperBirthPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"` // X 坐标
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"` // Y 坐标
}

func (x *PaperBirthPosition) Reset() {
	*x = PaperBirthPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperBirthPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperBirthPosition) ProtoMessage() {}

func (x *PaperBirthPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperBirthPosition.ProtoReflect.Descriptor instead.
func (*PaperBirthPosition) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{1}
}

func (x *PaperBirthPosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PaperBirthPosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 像素坐标
type PaperPixelPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"` // X 坐标
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"` // Y 坐标
}

func (x *PaperPixelPosition) Reset() {
	*x = PaperPixelPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperPixelPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperPixelPosition) ProtoMessage() {}

func (x *PaperPixelPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperPixelPosition.ProtoReflect.Descriptor instead.
func (*PaperPixelPosition) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{2}
}

func (x *PaperPixelPosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PaperPixelPosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 道具坐标
type PaperItemPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"` // X 坐标
	Y int32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"` // Y 坐标
}

func (x *PaperItemPosition) Reset() {
	*x = PaperItemPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperItemPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperItemPosition) ProtoMessage() {}

func (x *PaperItemPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperItemPosition.ProtoReflect.Descriptor instead.
func (*PaperItemPosition) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{3}
}

func (x *PaperItemPosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PaperItemPosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 此协议用作告知客户端，播放游戏开始前的动画、以及机器人玩家ID
type PaperVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat   map[string]*PaperBirthPosition `protobuf:"bytes,1,rep,name=seat,proto3" json:"seat,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 玩家游戏开始复活点位置。 playerID => position
	BotsID []string                       `protobuf:"bytes,2,rep,name=botsID,proto3" json:"botsID,omitempty"`                                                                                     // 机器人玩家ID
}

func (x *PaperVideo) Reset() {
	*x = PaperVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperVideo) ProtoMessage() {}

func (x *PaperVideo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperVideo.ProtoReflect.Descriptor instead.
func (*PaperVideo) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{4}
}

func (x *PaperVideo) GetSeat() map[string]*PaperBirthPosition {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *PaperVideo) GetBotsID() []string {
	if x != nil {
		return x.BotsID
	}
	return nil
}

// 此协议用作游戏开始时下发游戏数据
type PaperGameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSecond int32 `protobuf:"varint,1,opt,name=gameSecond,proto3" json:"gameSecond,omitempty"` // 一局游戏时长（秒）
}

func (x *PaperGameStart) Reset() {
	*x = PaperGameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperGameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperGameStart) ProtoMessage() {}

func (x *PaperGameStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperGameStart.ProtoReflect.Descriptor instead.
func (*PaperGameStart) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{5}
}

func (x *PaperGameStart) GetGameSecond() int32 {
	if x != nil {
		return x.GameSecond
	}
	return 0
}

// 此协议用作告知目标玩家：你是房主
// 房主负责发送机器人的坐标、转向、积分
// （当房主断线，换个人发送）
type PaperYouAreOwner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaperYouAreOwner) Reset() {
	*x = PaperYouAreOwner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperYouAreOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperYouAreOwner) ProtoMessage() {}

func (x *PaperYouAreOwner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperYouAreOwner.ProtoReflect.Descriptor instead.
func (*PaperYouAreOwner) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{6}
}

// 强制开始游戏。若人数不够，用 AI 来凑
type ForceStartWithAi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForceStartWithAi) Reset() {
	*x = ForceStartWithAi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceStartWithAi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceStartWithAi) ProtoMessage() {}

func (x *ForceStartWithAi) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceStartWithAi.ProtoReflect.Descriptor instead.
func (*ForceStartWithAi) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{7}
}

// 此协议用作同步玩家移动、转向、占地数据
type PaperMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string               `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 移动的玩家ID
	Pos      *PaperPlayerPosition `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`           // 新的坐标位置
	Dir      float32              `protobuf:"fixed32,3,opt,name=dir,proto3" json:"dir,omitempty"`         // 新的移动方向
	Score    float32              `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`     // 现在的积分。即表示占领地的面积占比，如： 27.02 %
	IsMoved  bool                 `protobuf:"varint,5,opt,name=isMoved,proto3" json:"isMoved,omitempty"`  // 是否正在移动
}

func (x *PaperMoveReq) Reset() {
	*x = PaperMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperMoveReq) ProtoMessage() {}

func (x *PaperMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperMoveReq.ProtoReflect.Descriptor instead.
func (*PaperMoveReq) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{8}
}

func (x *PaperMoveReq) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PaperMoveReq) GetPos() *PaperPlayerPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PaperMoveReq) GetDir() float32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PaperMoveReq) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PaperMoveReq) GetIsMoved() bool {
	if x != nil {
		return x.IsMoved
	}
	return false
}

// 此协议用作同步玩家移动、转向、占地数据、排名情况
type PaperMoveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string               `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 移动的玩家ID
	Pos      *PaperPlayerPosition `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`           // 新的坐标位置
	Dir      float32              `protobuf:"fixed32,3,opt,name=dir,proto3" json:"dir,omitempty"`         // 新的移动方向
	Rank     *PaperPlayerRankList `protobuf:"bytes,4,opt,name=rank,proto3" json:"rank,omitempty"`         // 玩家排名信息
	IsMoved  bool                 `protobuf:"varint,5,opt,name=isMoved,proto3" json:"isMoved,omitempty"`  // 是否正在移动
}

func (x *PaperMoveResp) Reset() {
	*x = PaperMoveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperMoveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperMoveResp) ProtoMessage() {}

func (x *PaperMoveResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperMoveResp.ProtoReflect.Descriptor instead.
func (*PaperMoveResp) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{9}
}

func (x *PaperMoveResp) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PaperMoveResp) GetPos() *PaperPlayerPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PaperMoveResp) GetDir() float32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PaperMoveResp) GetRank() *PaperPlayerRankList {
	if x != nil {
		return x.Rank
	}
	return nil
}

func (x *PaperMoveResp) GetIsMoved() bool {
	if x != nil {
		return x.IsMoved
	}
	return false
}

// 此协议用作描述玩家排名信息
type PaperPlayerRankList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ranks []*PaperPlayerRank `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"`
}

func (x *PaperPlayerRankList) Reset() {
	*x = PaperPlayerRankList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperPlayerRankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperPlayerRankList) ProtoMessage() {}

func (x *PaperPlayerRankList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperPlayerRankList.ProtoReflect.Descriptor instead.
func (*PaperPlayerRankList) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{10}
}

func (x *PaperPlayerRankList) GetRanks() []*PaperPlayerRank {
	if x != nil {
		return x.Ranks
	}
	return nil
}

// 此协议用作描述玩家排名信息
type PaperPlayerRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string  `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 玩家ID
	Score    float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`     // 现在的积分。即表示占领地的面积占比，如： 27.02 %
	Rank     int32   `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`        // 玩家排名
}

func (x *PaperPlayerRank) Reset() {
	*x = PaperPlayerRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperPlayerRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperPlayerRank) ProtoMessage() {}

func (x *PaperPlayerRank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperPlayerRank.ProtoReflect.Descriptor instead.
func (*PaperPlayerRank) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{11}
}

func (x *PaperPlayerRank) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PaperPlayerRank) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PaperPlayerRank) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// 此协议用作同步击杀行为
type PaperKill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Killer string `protobuf:"bytes,1,opt,name=killer,proto3" json:"killer,omitempty"` // 击杀者玩家ID
	Victim string `protobuf:"bytes,2,opt,name=victim,proto3" json:"victim,omitempty"` // 被击杀玩家ID
}

func (x *PaperKill) Reset() {
	*x = PaperKill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperKill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperKill) ProtoMessage() {}

func (x *PaperKill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperKill.ProtoReflect.Descriptor instead.
func (*PaperKill) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{12}
}

func (x *PaperKill) GetKiller() string {
	if x != nil {
		return x.Killer
	}
	return ""
}

func (x *PaperKill) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

// 此协议用作服务器向死亡玩家索要复活点坐标
type PaperQueryRevivePos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Victim string `protobuf:"bytes,1,opt,name=victim,proto3" json:"victim,omitempty"` // 死亡玩家ID
}

func (x *PaperQueryRevivePos) Reset() {
	*x = PaperQueryRevivePos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperQueryRevivePos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperQueryRevivePos) ProtoMessage() {}

func (x *PaperQueryRevivePos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperQueryRevivePos.ProtoReflect.Descriptor instead.
func (*PaperQueryRevivePos) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{13}
}

func (x *PaperQueryRevivePos) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

// 此协议用作同步被击杀玩家的复活行为
type PaperRevive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reviver string              `protobuf:"bytes,1,opt,name=reviver,proto3" json:"reviver,omitempty"` // 复活玩家ID
	Pos     *PaperBirthPosition `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`         // 复活点坐标
}

func (x *PaperRevive) Reset() {
	*x = PaperRevive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperRevive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperRevive) ProtoMessage() {}

func (x *PaperRevive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperRevive.ProtoReflect.Descriptor instead.
func (*PaperRevive) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{14}
}

func (x *PaperRevive) GetReviver() string {
	if x != nil {
		return x.Reviver
	}
	return ""
}

func (x *PaperRevive) GetPos() *PaperBirthPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 此协议用作广播玩家占领格子
type PaperCapture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string              `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 占领玩家ID
	Grid     *PaperPixelPosition `protobuf:"bytes,2,opt,name=grid,proto3" json:"grid,omitempty"`         // 占领的格子坐标
}

func (x *PaperCapture) Reset() {
	*x = PaperCapture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperCapture) ProtoMessage() {}

func (x *PaperCapture) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperCapture.ProtoReflect.Descriptor instead.
func (*PaperCapture) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{15}
}

func (x *PaperCapture) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PaperCapture) GetGrid() *PaperPixelPosition {
	if x != nil {
		return x.Grid
	}
	return nil
}

// 此协议用作广播玩家释放技能
type PaperReleaseSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID  string  `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"`    // 释放技能的玩家ID
	Dir       float32 `protobuf:"fixed32,2,opt,name=dir,proto3" json:"dir,omitempty"`            // 释放角度
	SkillType int32   `protobuf:"varint,3,opt,name=skillType,proto3" json:"skillType,omitempty"` // 技能类型
	Rocker    float32 `protobuf:"fixed32,4,opt,name=rocker,proto3" json:"rocker,omitempty"`      // 摇杆长度
}

func (x *PaperReleaseSkill) Reset() {
	*x = PaperReleaseSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperReleaseSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperReleaseSkill) ProtoMessage() {}

func (x *PaperReleaseSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperReleaseSkill.ProtoReflect.Descriptor instead.
func (*PaperReleaseSkill) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{16}
}

func (x *PaperReleaseSkill) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PaperReleaseSkill) GetDir() float32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PaperReleaseSkill) GetSkillType() int32 {
	if x != nil {
		return x.SkillType
	}
	return 0
}

func (x *PaperReleaseSkill) GetRocker() float32 {
	if x != nil {
		return x.Rocker
	}
	return 0
}

// 此协议用作广播玩家释放技能
type PaperItemGenerated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`     // 道具ID
	Type int32              `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 道具类型
	Pos  *PaperItemPosition `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`    // 道具坐标
}

func (x *PaperItemGenerated) Reset() {
	*x = PaperItemGenerated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperItemGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperItemGenerated) ProtoMessage() {}

func (x *PaperItemGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperItemGenerated.ProtoReflect.Descriptor instead.
func (*PaperItemGenerated) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{17}
}

func (x *PaperItemGenerated) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaperItemGenerated) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PaperItemGenerated) GetPos() *PaperItemPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 此协议用作广播玩家捡到道具
type PaperItemPick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"` // 捡到道具的玩家ID
	ItemID   int32  `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`    // 道具ID
	Type     int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`        // 道具类型
}

func (x *PaperItemPick) Reset() {
	*x = PaperItemPick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperItemPick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperItemPick) ProtoMessage() {}

func (x *PaperItemPick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperItemPick.ProtoReflect.Descriptor instead.
func (*PaperItemPick) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{18}
}

func (x *PaperItemPick) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PaperItemPick) GetItemID() int32 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *PaperItemPick) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 此协议用作广播游戏结果
type PaperGameEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank *PaperPlayerRankList `protobuf:"bytes,1,opt,name=rank,proto3" json:"rank,omitempty"` // 玩家排名信息
}

func (x *PaperGameEnd) Reset() {
	*x = PaperGameEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperGameEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperGameEnd) ProtoMessage() {}

func (x *PaperGameEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperGameEnd.ProtoReflect.Descriptor instead.
func (*PaperGameEnd) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{19}
}

func (x *PaperGameEnd) GetRank() *PaperPlayerRankList {
	if x != nil {
		return x.Rank
	}
	return nil
}

// 此协议用作告知客户端，播放游戏开始前的动画、以及玩家阵营、出生点坐标、机器人ID列表
type PaperV2Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seat       map[string]*PaperBirthPosition `protobuf:"bytes,1,rep,name=seat,proto3" json:"seat,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`             // 玩家游戏开始复活点位置。 playerID => position
	TeamPlayer map[string]string              `protobuf:"bytes,2,rep,name=teamPlayer,proto3" json:"teamPlayer,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 玩家队伍信息。 playerID => teamID
	BotsID     []string                       `protobuf:"bytes,3,rep,name=botsID,proto3" json:"botsID,omitempty"`                                                                                                 // 机器人玩家ID
}

func (x *PaperV2Video) Reset() {
	*x = PaperV2Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperV2Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperV2Video) ProtoMessage() {}

func (x *PaperV2Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperV2Video.ProtoReflect.Descriptor instead.
func (*PaperV2Video) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{20}
}

func (x *PaperV2Video) GetSeat() map[string]*PaperBirthPosition {
	if x != nil {
		return x.Seat
	}
	return nil
}

func (x *PaperV2Video) GetTeamPlayer() map[string]string {
	if x != nil {
		return x.TeamPlayer
	}
	return nil
}

func (x *PaperV2Video) GetBotsID() []string {
	if x != nil {
		return x.BotsID
	}
	return nil
}

// 此协议用作广播游戏结果
type PaperV2GameEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"` // 获胜阵营ID
	Score  int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`  // 分数
}

func (x *PaperV2GameEnd) Reset() {
	*x = PaperV2GameEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperV2GameEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperV2GameEnd) ProtoMessage() {}

func (x *PaperV2GameEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperV2GameEnd.ProtoReflect.Descriptor instead.
func (*PaperV2GameEnd) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{21}
}

func (x *PaperV2GameEnd) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *PaperV2GameEnd) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// 此协议用作广播阵营占领中心区域达到 80%
type PaperV2Enter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"` // 获胜阵营ID
}

func (x *PaperV2Enter) Reset() {
	*x = PaperV2Enter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperV2Enter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperV2Enter) ProtoMessage() {}

func (x *PaperV2Enter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperV2Enter.ProtoReflect.Descriptor instead.
func (*PaperV2Enter) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{22}
}

func (x *PaperV2Enter) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

// 此协议用作广播阵营占领中心区域低于 50%
type PaperV2Exit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"` // 获胜阵营ID
}

func (x *PaperV2Exit) Reset() {
	*x = PaperV2Exit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperV2Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperV2Exit) ProtoMessage() {}

func (x *PaperV2Exit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperV2Exit.ProtoReflect.Descriptor instead.
func (*PaperV2Exit) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{23}
}

func (x *PaperV2Exit) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

// 此协议用作广播阵营分数变动
type PaperV2ScoreAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamID string `protobuf:"bytes,1,opt,name=teamID,proto3" json:"teamID,omitempty"` // 阵营ID
	Score  int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`  // 分数
}

func (x *PaperV2ScoreAdd) Reset() {
	*x = PaperV2ScoreAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_paperio_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaperV2ScoreAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperV2ScoreAdd) ProtoMessage() {}

func (x *PaperV2ScoreAdd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paperio_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperV2ScoreAdd.ProtoReflect.Descriptor instead.
func (*PaperV2ScoreAdd) Descriptor() ([]byte, []int) {
	return file_proto_paperio_proto_rawDescGZIP(), []int{24}
}

func (x *PaperV2ScoreAdd) GetTeamID() string {
	if x != nil {
		return x.TeamID
	}
	return ""
}

func (x *PaperV2ScoreAdd) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_paperio_proto protoreflect.FileDescriptor

var file_proto_paperio_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x22, 0x31,
	0x0a, 0x13, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x59, 0x22, 0x30, 0x0a, 0x12, 0x50, 0x61, 0x70, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x59, 0x22, 0x30, 0x0a, 0x12, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x69, 0x78, 0x65,
	0x6c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x59, 0x22, 0x2f, 0x0a, 0x11, 0x50, 0x61, 0x70, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x59, 0x22, 0xad, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61,
	0x70, 0x65, 0x72, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x73,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x74, 0x73, 0x49, 0x44,
	0x1a, 0x54, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x42, 0x69,
	0x72, 0x74, 0x68, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x0e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x67, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x50, 0x61, 0x70, 0x65,
	0x72, 0x59, 0x6f, 0x75, 0x41, 0x72, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x12, 0x0a, 0x10,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x57, 0x69, 0x74, 0x68, 0x41, 0x69,
	0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x50, 0x61, 0x70, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2e, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x22,
	0xb9, 0x01, 0x0a, 0x0d, 0x50, 0x61, 0x70, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2e, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12,
	0x30, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x22, 0x45, 0x0a, 0x13, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65,
	0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x05, 0x72, 0x61, 0x6e,
	0x6b, 0x73, 0x22, 0x57, 0x0a, 0x0f, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x3b, 0x0a, 0x09, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x4b, 0x69, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x22, 0x2d, 0x0a, 0x13, 0x50, 0x61, 0x70, 0x65,
	0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x76, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x22, 0x56, 0x0a, 0x0b, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x52, 0x65, 0x76, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x69, 0x76, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x76, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x2d, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x42, 0x69, 0x72,
	0x74, 0x68, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22,
	0x5b, 0x0a, 0x0c, 0x50, 0x61, 0x70, 0x65, 0x72, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2f, 0x0a, 0x04, 0x67,
	0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x67, 0x72, 0x69, 0x64, 0x22, 0x77, 0x0a, 0x11,
	0x50, 0x61, 0x70, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x64, 0x69, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x12, 0x50, 0x61, 0x70, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x2c, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70,
	0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x57, 0x0a,
	0x0d, 0x50, 0x61, 0x70, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x69, 0x63, 0x6b, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74,
	0x65, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x50, 0x61, 0x70, 0x65, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50,
	0x61, 0x70, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0xb7, 0x02, 0x0a, 0x0c, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x56, 0x32, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x33, 0x0a, 0x04, 0x73, 0x65, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x56, 0x32, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x53,
	0x65, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x45,
	0x0a, 0x0a, 0x74, 0x65, 0x61, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x61, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x56, 0x32, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x74, 0x65, 0x61, 0x6d, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x74, 0x73, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x74, 0x73, 0x49, 0x44, 0x1a, 0x54, 0x0a,
	0x09, 0x53, 0x65, 0x61, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x2e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x3d, 0x0a, 0x0f, 0x54, 0x65, 0x61, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x61, 0x70, 0x65, 0x72, 0x56, 0x32, 0x47, 0x61, 0x6d,
	0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x50, 0x61, 0x70, 0x65, 0x72, 0x56, 0x32, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x0b, 0x50, 0x61,
	0x70, 0x65, 0x72, 0x56, 0x32, 0x45, 0x78, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x44, 0x22, 0x3f, 0x0a, 0x0f, 0x50, 0x61, 0x70, 0x65, 0x72, 0x56, 0x32, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x41, 0x64, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_paperio_proto_rawDescOnce sync.Once
	file_proto_paperio_proto_rawDescData = file_proto_paperio_proto_rawDesc
)

func file_proto_paperio_proto_rawDescGZIP() []byte {
	file_proto_paperio_proto_rawDescOnce.Do(func() {
		file_proto_paperio_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_paperio_proto_rawDescData)
	})
	return file_proto_paperio_proto_rawDescData
}

var file_proto_paperio_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_paperio_proto_goTypes = []interface{}{
	(*PaperPlayerPosition)(nil), // 0: paperio.PaperPlayerPosition
	(*PaperBirthPosition)(nil),  // 1: paperio.PaperBirthPosition
	(*PaperPixelPosition)(nil),  // 2: paperio.PaperPixelPosition
	(*PaperItemPosition)(nil),   // 3: paperio.PaperItemPosition
	(*PaperVideo)(nil),          // 4: paperio.PaperVideo
	(*PaperGameStart)(nil),      // 5: paperio.PaperGameStart
	(*PaperYouAreOwner)(nil),    // 6: paperio.PaperYouAreOwner
	(*ForceStartWithAi)(nil),    // 7: paperio.ForceStartWithAi
	(*PaperMoveReq)(nil),        // 8: paperio.PaperMoveReq
	(*PaperMoveResp)(nil),       // 9: paperio.PaperMoveResp
	(*PaperPlayerRankList)(nil), // 10: paperio.PaperPlayerRankList
	(*PaperPlayerRank)(nil),     // 11: paperio.PaperPlayerRank
	(*PaperKill)(nil),           // 12: paperio.PaperKill
	(*PaperQueryRevivePos)(nil), // 13: paperio.PaperQueryRevivePos
	(*PaperRevive)(nil),         // 14: paperio.PaperRevive
	(*PaperCapture)(nil),        // 15: paperio.PaperCapture
	(*PaperReleaseSkill)(nil),   // 16: paperio.PaperReleaseSkill
	(*PaperItemGenerated)(nil),  // 17: paperio.PaperItemGenerated
	(*PaperItemPick)(nil),       // 18: paperio.PaperItemPick
	(*PaperGameEnd)(nil),        // 19: paperio.PaperGameEnd
	(*PaperV2Video)(nil),        // 20: paperio.PaperV2Video
	(*PaperV2GameEnd)(nil),      // 21: paperio.PaperV2GameEnd
	(*PaperV2Enter)(nil),        // 22: paperio.PaperV2Enter
	(*PaperV2Exit)(nil),         // 23: paperio.PaperV2Exit
	(*PaperV2ScoreAdd)(nil),     // 24: paperio.PaperV2ScoreAdd
	nil,                         // 25: paperio.PaperVideo.SeatEntry
	nil,                         // 26: paperio.PaperV2Video.SeatEntry
	nil,                         // 27: paperio.PaperV2Video.TeamPlayerEntry
}
var file_proto_paperio_proto_depIdxs = []int32{
	25, // 0: paperio.PaperVideo.seat:type_name -> paperio.PaperVideo.SeatEntry
	0,  // 1: paperio.PaperMoveReq.pos:type_name -> paperio.PaperPlayerPosition
	0,  // 2: paperio.PaperMoveResp.pos:type_name -> paperio.PaperPlayerPosition
	10, // 3: paperio.PaperMoveResp.rank:type_name -> paperio.PaperPlayerRankList
	11, // 4: paperio.PaperPlayerRankList.ranks:type_name -> paperio.PaperPlayerRank
	1,  // 5: paperio.PaperRevive.pos:type_name -> paperio.PaperBirthPosition
	2,  // 6: paperio.PaperCapture.grid:type_name -> paperio.PaperPixelPosition
	3,  // 7: paperio.PaperItemGenerated.pos:type_name -> paperio.PaperItemPosition
	10, // 8: paperio.PaperGameEnd.rank:type_name -> paperio.PaperPlayerRankList
	26, // 9: paperio.PaperV2Video.seat:type_name -> paperio.PaperV2Video.SeatEntry
	27, // 10: paperio.PaperV2Video.teamPlayer:type_name -> paperio.PaperV2Video.TeamPlayerEntry
	1,  // 11: paperio.PaperVideo.SeatEntry.value:type_name -> paperio.PaperBirthPosition
	1,  // 12: paperio.PaperV2Video.SeatEntry.value:type_name -> paperio.PaperBirthPosition
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_paperio_proto_init() }
func file_proto_paperio_proto_init() {
	if File_proto_paperio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_paperio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperPlayerPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperBirthPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperPixelPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperItemPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperGameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperYouAreOwner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceStartWithAi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperMoveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperPlayerRankList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperPlayerRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperKill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperQueryRevivePos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperRevive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperCapture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperReleaseSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperItemGenerated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperItemPick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperGameEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperV2Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperV2GameEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperV2Enter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperV2Exit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_paperio_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaperV2ScoreAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_paperio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_paperio_proto_goTypes,
		DependencyIndexes: file_proto_paperio_proto_depIdxs,
		MessageInfos:      file_proto_paperio_proto_msgTypes,
	}.Build()
	File_proto_paperio_proto = out.File
	file_proto_paperio_proto_rawDesc = nil
	file_proto_paperio_proto_goTypes = nil
	file_proto_paperio_proto_depIdxs = nil
}
